<?php
namespace AppBundle\Classes;

class GoCompare
{
    public static $models = [
        26 => ['make' => 'Apple', 'model' => 'iPhone 6S', 'memory' => 128],
        27 => ['make' => 'Apple', 'model' => 'iPhone 6S', 'memory' => 16],
        28 => ['make' => 'Apple', 'model' => 'iPhone 6S', 'memory' => 32],
        29 => ['make' => 'Apple', 'model' => 'iPhone 6S', 'memory' => 64],
        30 => ['make' => 'Apple', 'model' => 'iPhone 6S Plus', 'memory' => 128],
        31 => ['make' => 'Apple', 'model' => 'iPhone 6S Plus', 'memory' => 16],
        32 => ['make' => 'Apple', 'model' => 'iPhone 6S Plus', 'memory' => 32],
        33 => ['make' => 'Apple', 'model' => 'iPhone 6S Plus', 'memory' => 64],
        34 => ['make' => 'Apple', 'model' => 'iPhone 7', 'memory' => 128],
        35 => ['make' => 'Apple', 'model' => 'iPhone 7', 'memory' => 256],
        36 => ['make' => 'Apple', 'model' => 'iPhone 7', 'memory' => 32],
        37 => ['make' => 'Apple', 'model' => 'iPhone 7 Plus', 'memory' => 128],
        38 => ['make' => 'Apple', 'model' => 'iPhone 7 Plus', 'memory' => 256],
        39 => ['make' => 'Apple', 'model' => 'iPhone 7 Plus', 'memory' => 32],
        40 => ['make' => 'Apple', 'model' => 'iPhone SE', 'memory' => 16],
        41 => ['make' => 'Apple', 'model' => 'iPhone SE', 'memory' => 64],
        814 => ['make' => 'Apple', 'model' => 'iPhone 8', 'memory' => 64],
        815 => ['make' => 'Apple', 'model' => 'iPhone 8', 'memory' => 256],
        816 => ['make' => 'Apple', 'model' => 'iPhone 8 Plus', 'memory' => 64],
        817 => ['make' => 'Apple', 'model' => 'iPhone 8 Plus', 'memory' => 256],
        818 => ['make' => 'Apple', 'model' => 'iPhone X', 'memory' => 64],
        819 => ['make' => 'Apple', 'model' => 'iPhone X', 'memory' => 256],
        806 => ['make' => 'Apple', 'model' => 'iPhone SE', 'memory' => 32],
        807 => ['make' => 'Apple', 'model' => 'iPhone SE', 'memory' => 128],
        1440 => ['make' => 'Apple', 'model' => 'iPhone XR', 'memory' => 64],
        1441 => ['make' => 'Apple', 'model' => 'iPhone XR', 'memory' => 128],
        1442 => ['make' => 'Apple', 'model' => 'iPhone XR', 'memory' => 256],
        1443 => ['make' => 'Apple', 'model' => 'iPhone XS', 'memory' => 64],
        1444 => ['make' => 'Apple', 'model' => 'iPhone XS', 'memory' => 256],
        1445 => ['make' => 'Apple', 'model' => 'iPhone XS', 'memory' => 512],
        1446 => ['make' => 'Apple', 'model' => 'iPhone XS Max', 'memory' => 64],
        1447 => ['make' => 'Apple', 'model' => 'iPhone XS Max', 'memory' => 256],
        1448 => ['make' => 'Apple', 'model' => 'iPhone XS Max', 'memory' => 512],
        1707 => ['make' => 'Apple', 'model' => 'iPhone 11', 'memory' => 64],
        1708 => ['make' => 'Apple', 'model' => 'iPhone 11', 'memory' => 128],
        1709 => ['make' => 'Apple', 'model' => 'iPhone 11', 'memory' => 256],
        1710 => ['make' => 'Apple', 'model' => 'iPhone 11 Pro', 'memory' => 64],
        1711 => ['make' => 'Apple', 'model' => 'iPhone 11 Pro', 'memory' => 256],
        1712 => ['make' => 'Apple', 'model' => 'iPhone 11 Pro', 'memory' => 512],
        1713 => ['make' => 'Apple', 'model' => 'iPhone 11 Pro Max', 'memory' => 64],
        1714 => ['make' => 'Apple', 'model' => 'iPhone 11 Pro Max', 'memory' => 256],
        1715 => ['make' => 'Apple', 'model' => 'iPhone 11 Pro Max', 'memory' => 512],
        1723 => ['make' => 'Apple', 'model' => 'iPhone 8', 'memory' => 128],
        1724 => ['make' => 'Apple', 'model' => 'iPhone 8 Plus', 'memory' => 128],

        // no longer supported by gocompare.
        // 215 => ['make' => 'Samsung', 'model' => 'Galaxy S6', 'memory' => 128],
        // 216 => ['make' => 'Samsung', 'model' => 'Galaxy S6', 'memory' => 32],
        // 217 => ['make' => 'Samsung', 'model' => 'Galaxy S6', 'memory' => 64],
        // 218 => ['make' => 'Samsung', 'model' => 'Galaxy S6 Edge', 'memory' => 128],
        // 219 => ['make' => 'Samsung', 'model' => 'Galaxy S6 Edge', 'memory' => 32],
        // 220 => ['make' => 'Samsung', 'model' => 'Galaxy S6 Edge', 'memory' => 64],
        221 => ['make' => 'Samsung', 'model' => 'Galaxy S6 Edge+', 'memory' => 32],
        222 => ['make' => 'Samsung', 'model' => 'Galaxy S6 Edge+', 'memory' => 64],
        223 => ['make' => 'Samsung', 'model' => 'Galaxy S7', 'memory' => 32],
        224 => ['make' => 'Samsung', 'model' => 'Galaxy S7 Edge', 'memory' => 32],
        808 => ['make' => 'Samsung', 'model' => 'Galaxy S8', 'memory' => 64],
        809 => ['make' => 'Samsung', 'model' => 'Galaxy S8+', 'memory' => 64],
        820 => ['make' => 'Samsung', 'model' => 'Galaxy Note 8', 'memory' => 64],
        1432 => ['make' => 'Samsung', 'model' => 'Galaxy Note 9', 'memory' => 128],
        1433 => ['make' => 'Samsung', 'model' => 'Galaxy Note 9', 'memory' => 512],
        1449 => ['make' => 'Samsung', 'model' => 'Galaxy J6', 'memory' => 32],
        1239 => ['make' => 'Samsung', 'model' => 'Galaxy S9', 'memory' => 64],
        1240 => ['make' => 'Samsung', 'model' => 'Galaxy S9+', 'memory' => 128],
        1463 => ['make' => 'Samsung', 'model' => 'Galaxy A6', 'memory' => 32],
        1479 => ['make' => 'Samsung', 'model' => 'Galaxy A7 (2018)', 'memory' => 64],
        1480 => ['make' => 'Samsung', 'model' => 'Galaxy A9 (2018)', 'memory' => 128],
        1530 => ['make' => 'Samsung', 'model' => 'Galaxy S10+', 'memory' => 128],
        1533 => ['make' => 'Samsung', 'model' => 'Galaxy S10', 'memory' => 128],
        1534 => ['make' => 'Samsung', 'model' => 'Galaxy S10', 'memory' => 512],
        1628 => ['make' => 'Samsung', 'model' => 'Galaxy 50', 'memory' => 64],
        1629 => ['make' => 'Samsung', 'model' => 'Galaxy 50', 'memory' => 128],
        1630 => ['make' => 'Samsung', 'model' => 'Galaxy A70', 'memory' => 128],
        1699 => ['make' => 'Samsung', 'model' => 'Galaxy Note 10', 'memory' => 256],
        1700 => ['make' => 'Samsung', 'model' => 'Galaxy Note 10 Plus', 'memory' => 256],
        1701 => ['make' => 'Samsung', 'model' => 'Galaxy Note 10 Plus 5G', 'memory' => 256],
        1706 => ['make' => 'Samsung', 'model' => 'Galaxy Note 10 Plus 5G', 'memory' => 512],
        1720 => ['make' => 'Samsung', 'model' => 'Galaxy A10', 'memory' => 32],
        1721 => ['make' => 'Samsung', 'model' => 'Galaxy S10 5G', 'memory' => 256],
        1722 => ['make' => 'Samsung', 'model' => 'Galaxy S10 5G', 'memory' => 512],
        1752 => ['make' => 'Samsung', 'model' => 'Galaxy S10 5G', 'memory' => 32],

        1412 => ['make' => 'Huawei', 'model' => 'P20', 'memory' => 128],
        1413 => ['make' => 'Huawei', 'model' => 'P20 Lite', 'memory' => 64],
        1414 => ['make' => 'Huawei', 'model' => 'P20 Pro', 'memory' => 128],
        1450 => ['make' => 'Huawei', 'model' => 'Honor 9', 'memory' => 64],
        1453 => ['make' => 'Huawei', 'model' => 'Honor 7X', 'memory' => 64],
        1454 => ['make' => 'Huawei', 'model' => 'P Smart', 'memory' => 32],
        1456 => ['make' => 'Huawei', 'model' => 'Honor Play', 'memory' => 64],
        1457 => ['make' => 'Huawei', 'model' => 'Mate 20 Pro', 'memory' => 128],
        1429 => ['make' => 'Huawei', 'model' => 'P8 Lite (2017)', 'memory' => 16],
        1430 => ['make' => 'Huawei', 'model' => 'P Smart', 'memory' => 32],
        1424 => ['make' => 'Huawei', 'model' => 'Honor 10', 'memory' => 64],
        1475 => ['make' => 'Huawei', 'model' => 'Honor 8', 'memory' => 32],
        1483 => ['make' => 'Huawei', 'model' => 'Honor 10', 'memory' => 128],
        1528 => ['make' => 'Huawei', 'model' => 'P Smart 2019', 'memory' => 64],
        1624 => ['make' => 'Huawei', 'model' => 'P30', 'memory' => 128],
        1625 => ['make' => 'Huawei', 'model' => 'P30 Pro', 'memory' => 128],
        1739 => ['make' => 'Huawei', 'model' => 'Mate 20 X 5G', 'memory' => 128],
        1740 => ['make' => 'Huawei', 'model' => 'Mate 20 X 5G', 'memory' => 256],
        1753 => ['make' => 'Huawei', 'model' => 'Mate 20', 'memory' => 256],
        1754 => ['make' => 'Huawei', 'model' => 'Honor 20 Pro', 'memory' => 128],
        1755 => ['make' => 'Huawei', 'model' => 'Honor 20 Pro', 'memory' => 256],
        1758 => ['make' => 'Huawei', 'model' => 'P30 Lite', 'memory' => 128],
        1759 => ['make' => 'Huawei', 'model' => 'Honor 20', 'memory' => 128],

        1417 => ['make' => 'Motorola', 'model' => 'Moto X4', 'memory' => 64],
        1418 => ['make' => 'Motorola', 'model' => 'Moto G5s', 'memory' => 32],
        1419 => ['make' => 'Motorola', 'model' => 'Moto G5s Plus', 'memory' => 64],
        1420 => ['make' => 'Motorola', 'model' => 'Moto Z2 Force', 'memory' => 64],
        1421 => ['make' => 'Motorola', 'model' => 'Moto E4 Plus', 'memory' => 16],

        1428 => ['make' => 'LG', 'model' => 'G7 ThinQ', 'memory' => 64],

        1416 => ['make' => 'Sony', 'model' => 'Xperia XA2', 'memory' => 32],
        1462 => ['make' => 'Sony', 'model' => 'Xperia XZ3', 'memory' => 64],
        1744 => ['make' => 'Sony', 'model' => 'Xperia L3', 'memory' => 32],
        1751 => ['make' => 'Sony', 'model' => 'Xperia 5', 'memory' => 128],

        827 => ['make' => 'Google', 'model' => 'Pixel 2', 'memory' => 64],
        835 => ['make' => 'Google', 'model' => 'Pixel 2', 'memory' => 128],
        828 => ['make' => 'Google', 'model' => 'Pixel 2 XL', 'memory' => 64],
        836 => ['make' => 'Google', 'model' => 'Pixel 2 XL', 'memory' => 128],
        1464 => ['make' => 'Google', 'model' => 'Pixel 3', 'memory' => 64],
        1465 => ['make' => 'Google', 'model' => 'Pixel 3 XL', 'memory' => 64],
        1645 => ['make' => 'Google', 'model' => 'Pixel 3a', 'memory' => 64],
        1646 => ['make' => 'Google', 'model' => 'Pixel 3a XL', 'memory' => 64],
        1747 => ['make' => 'Google', 'model' => 'Pixel 4', 'memory' => 64],
        1748 => ['make' => 'Google', 'model' => 'Pixel 4', 'memory' => 128128],
        1749 => ['make' => 'Google', 'model' => 'Pixel 4 XL', 'memory' => 64],
        1750 => ['make' => 'Google', 'model' => 'Pixel 4 XL', 'memory' => 128],

        1477 => ['make' => 'Nokia', 'model' => '7.1', 'memory' => 32],

        182 => ['make' => 'OnePlus', 'model' => 'Three', 'memory' => 64],
        183 => ['make' => 'OnePlus', 'model' => 'Two', 'memory' => 16],
        184 => ['make' => 'OnePlus', 'model' => 'X', 'memory' => 16],
        824 => ['make' => 'OnePlus', 'model' => '5', 'memory' => 64],
        825 => ['make' => 'OnePlus', 'model' => '5T', 'memory' => 64],
        1425 => ['make' => 'OnePlus', 'model' => '6', 'memory' => 64],
        1426 => ['make' => 'OnePlus', 'model' => '6', 'memory' => 128],
        1427 => ['make' => 'OnePlus', 'model' => '6', 'memory' => 256],
        1466 => ['make' => 'OnePlus', 'model' => '6T', 'memory' => 128],
        1467 => ['make' => 'OnePlus', 'model' => '6T', 'memory' => 256],
        1647 => ['make' => 'OnePlus', 'model' => '7 Pro', 'memory' => 128],
        1648 => ['make' => 'OnePlus', 'model' => '7 Pro', 'memory' => 256],
        1745 => ['make' => 'OnePlus', 'model' => '7T', 'memory' => 128],
        1746 => ['make' => 'OnePlus', 'model' => '7T', 'memory' => 256],

        1733 => ['make' => 'Oppo', 'model' => 'Reno', 'memory' => 256],
        1734 => ['make' => 'Oppo', 'model' => 'Reno 10x Zoom', 'memory' => 256],
        1736 => ['make' => 'Oppo', 'model' => 'RX17 Pro', 'memory' => 128],
        1737 => ['make' => 'Oppo', 'model' => 'Reno Z', 'memory' => 128],
        1738 => ['make' => 'Oppo', 'model' => 'Find X', 'memory' => 256],
        1760 => ['make' => 'Oppo', 'model' => 'Reno 5G', 'memory' => 256],

        1741 => ['make' => 'Xiaomi', 'model' => 'Redmi Note 7', 'memory' => 64],
        1742 => ['make' => 'Xiaomi', 'model' => 'Mi 9T', 'memory' => 64],
        1743 => ['make' => 'Xiaomi', 'model' => 'Mi 9T Pro', 'memory' => 128],
    ];
}
