---
ses_username: "{{ lookup('credstash', 'prod/server/ses_username', region='eu-west-1') }}"
ses_password: "{{ lookup('credstash', 'prod/server/ses_password', region='eu-west-1') }}"

web_private_key: "{{ lookup('credstash', 'prod/server/idrsa', region='eu-west-1') }}"
web_public_key: "{{ lookup('credstash', 'prod/server/idrsa.pub', region='eu-west-1') }}"

jenkins_private_key: "{{ lookup('credstash', 'prod/server/jenkins_idrsa', region='eu-west-1') }}"
jenkins_public_key: "{{ lookup('credstash', 'prod/server/jenkins_idrsa.pub', region='eu-west-1') }}"

logs_access_key: "{{ lookup('credstash', 'prod/fluentd/access_key', region='eu-west-1') }}"
logs_secret_key: "{{ lookup('credstash', 'prod/fluentd/access_secret', region='eu-west-1') }}"

app_ses_username: "{{ lookup('credstash', 'prod/app/ses_username', region='eu-west-1') }}"
app_ses_password: "{{ lookup('credstash', 'prod/app/ses_password', region='eu-west-1') }}"
session_secret: "{{ lookup('credstash', 'prod/app/session_secret', region='eu-west-1') }}"
facebook_appid: "{{ lookup('credstash', 'prod/app/facebook_appid', region='eu-west-1') }}"
facebook_secret: "{{ lookup('credstash', 'prod/app/facebook_secret', region='eu-west-1') }}"
mongodb_url: "{{ lookup('credstash', 'prod/app/mongodb_url', region='eu-west-1') }}"
github_token: "{{ lookup('credstash', 'prod/server/github_token', region='eu-west-1') }}"

mailchimp_apikey: "{{ lookup('credstash', 'prod/app/mailchimp_apikey', region='eu-west-1') }}"
mailchimp_prelaunch_list: "{{ lookup('credstash', 'prod/app/mailchimp_prelaunch_list', region='eu-west-1') }}"
google_apikey: "{{ lookup('credstash', 'prod/app/google_apikey', region='eu-west-1') }}"
gocardless_apikey: "{{ lookup('credstash', 'prod/app/gocardless_apikey', region='eu-west-1') }}"

sosure_path: /var/sosure/current/web

db_replication_name: prod
db_authorization: enabled
