- name: varnish
  apt: pkg=varnish
- name: apache php
  apt: pkg=apache2,php5,libapache2-mod-php5,php5-mcrypt,php-pear,php5-dev,php5-curl state=latest
- name: for mongo pecl
  apt: pkg=pkg-config,libssl-dev,libsslcommon2-dev,libsasl2-dev,libpcre3-dev state=latest
- pear: name=pecl/mongo state=present
- name: php mongo
  template: src=templates/mongo.ini dest=/etc/php5/mods-available/mongo.ini
- name: enable php mongo
  command: php5enmod mongo
- name: node-bower
  npm: name=bower global=yes
- name: node-grunt
  npm: name=grunt global=yes
- name: node-grunt-cli
  npm: name=grunt-cli global=yes

- get_url: url=https://s3-eu-west-1.amazonaws.com/aws-codedeploy-eu-west-1/latest/install dest=/usr/local/share/install-code-deploy mode=0755
- command: /usr/local/share/install-code-deploy auto

- name: awslogs conf
  template: src=templates/awslogs.conf dest=/tmp/awslogs.conf
- get_url: url=https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py dest=/usr/local/share/awslogs-agent-setup.py mode=0755
- command: /usr/local/share/awslogs-agent-setup.py -n -r eu-west-1 -c /tmp/awslogs.conf

- command: ansible-galaxy install carlosbuenosvinos.ansistrano-deploy