- name: apache php
  apt: pkg=apache2,php5,libapache2-mod-php5,php5-mcrypt,php-pear,php5-dev,php5-curl state=latest
- name: for mongo pecl
  apt: pkg=pkg-config,libssl-dev,libsslcommon2-dev,libsasl2-dev,libpcre3-dev state=latest
- pear: name=pecl/mongo state=present
- name: php mongo
  template: src=templates/mongo.ini dest=/etc/php5/mods-available/mongo.ini
- name: enable php mongo
  command: php5enmod mongo
- name: node-bower
  npm: name=bower global=yes
- name: node-grunt
  npm: name=grunt global=yes
- name: node-grunt-cli
  npm: name=grunt-cli global=yes
