imports:
    - { resource: config.yml }

framework:
    # 10.* required for the elb load balancing health check
    trusted_hosts: ['wearesosure.com', '10\.\d+\.\d+\.\d+']
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    default_mailer: ses
    mailers:
        default:
            transport:  "%ses_mailer_transport%"
            host:       "%ses_mailer_host%"
            port:       "%ses_mailer_port%"
            username:   "%ses_mailer_user%"
            password:   "%ses_mailer_password%"
            encryption: "%ses_mailer_encryption%"
            spool:      { type: memory }
        invite:
            transport:  "%blue_mailer_transport%"
            host:       "%blue_mailer_host%"
            port:       "%blue_mailer_port%"
            username:   "%blue_mailer_user%"
            password:   "%blue_mailer_password%"
            encryption: "%blue_mailer_encryption%"
            spool:      { type: memory }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

staffim_rollbar:
    # Rollbar access token
    access_token: %rollbar_access_token%
    # PHP error level (see http://php.net/manual/en/function.error-reporting.php)
    error_level: -1
    # Values from scrub.parameters are replaced by the key for specified exceptions
    scrub:
        exceptions:
            - PDOException
        parameters:
            key: unknown