imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    mongo.session.options:
        database: "%mongodb_db%"
        collection: session
    cognito_developer_login: 'login.so-sure.com'
    default_sender_address: 'hello@wearesosure.com'
    default_sender_name: 'so-sure'
    report_excluded_policy_ids:
        - 57d829aa04e76f403c74ab39 # Dylan
        - 57ef7c67a6b37e5b2359e995 # Patrick
    sosure_ips:
        - 86.26.167.103

framework:
    #esi:             ~
    translator: { fallbacks: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: snc_redis.session.handler
        cookie_httponly: true
    fragments:       ~
    http_method_override: true
    validation: { enabled: true, enable_annotations: true }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fb_appid: "%fb_appid%"
        fb_pixel_id: "%fb_pixel_id%"
        fb_og_namespace: "%fb_og_namespace%"
        cdn_url: "https://cdn.so-sure.com"
        heap_id: "%heap_id%"
        google_analytics: "%google_analytics%"
        ga_tag_manager_env: "%ga_tag_manager_env%"
        pca_webkey: "%pca_webkey%"
        branch_key: "%branch_key%"
        drift_key: "%drift_key%"
        use_cdn: true
        branch_pot_url: "%branch_pot_url%"
        branch_share_url: "%branch_share_url%"
        branch_policy_url: "%branch_policy_url%"
        branch_card_url: "%branch_card_url%"
        expected_claim_frequency: "0.2"
        consumer_payout: "17.2"
        ipt_rebate: "1.5"
        davies_ip: "%davies_ip%"
        environment: "%kernel.environment%"
        digits_consumer_key: "%digits_consumer_key%"

doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_url%"
            options: {}
    default_database: "%mongodb_db%"
    document_managers:
        default:
            auto_mapping: true
            retry_connect: 5
            retry_query: 1
            mappings:
                gedmo_loggable:
                    type: annotation
                    prefix: Gedmo\Loggable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Document"
                    alias: GedmoLoggable
                    is_bundle: false
    default_commit_options:
        timeout: 2000  # integer >= -1

# Swiftmailer Configuration
swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport:  "%ses_mailer_transport%"
            host:       "%ses_mailer_host%"
            port:       "%ses_mailer_port%"
            username:   "%ses_mailer_user%"
            password:   "%ses_mailer_password%"
            encryption: "%ses_mailer_encryption%"
            spool:      { type: service, id: snc_redis.swiftmailer.spool }

monolog:
    channels: ['receperio']

assetic:
    bundles:        [ AppBundle, FOSUserBundle, TwigBundle ]
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        sass:
            bin:        /usr/local/bin/sass
            apply_to:   '\.scss$'
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: AppBundle\Document\User
    registration:
        form:
            type: AppBundle\Form\Type\RegistrationFormType
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: email/password_resetting.email.twig
            from_email:
                address:        hello@wearesosure.com
                sender_name:    so-sure

hwi_oauth:
    connect:
        account_connector: app.user
        confirmation: false
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%fb_appid%"
            client_secret:       "%fb_secret%"
            scope:               "email"
            options:
                #display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions
                appsecret_proof: true
            infos_url:     "https://graph.facebook.com/me?fields=id,first_name,last_name,email"
            paths:
                email:     email
                firstname: first_name
                lastname:  last_name
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [AppBundle]
        directories: ["%kernel.root_dir%/../src"]

jms_security_extra:
    expressions: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%redis_default_dsn%"
        session:
            type: predis
            alias: session
            dsn: "%redis_session_dsn%"
            logging: false
        mailer:
            type: predis
            alias: mailer
            dsn: "%redis_mailer_dsn%"
            logging: false

    session:
        client: session
        ttl: 1200 # 20 minutes - refreshed on page access

    swiftmailer:
        client: mailer
        key: swiftmailer

stof_doctrine_extensions:
  mongodb:
    default:
      loggable: true

oneup_flysystem:
    adapters:
        s3admin:
            awss3v3:
                client: aws.s3
                bucket: admin.so-sure.com
                prefix: "%kernel.environment%"
        s3support:
            awss3v3:
                client: aws.s3
                bucket: help.so-sure.com
                prefix: "%kernel.environment%"
        s3blog:
            awss3v3:
                client: aws.s3
                bucket: blog.so-sure.com
                prefix: "%kernel.environment%"
        s3policy:
            awss3v3:
                client: aws.s3
                bucket: policy.so-sure.com
                prefix: "%kernel.environment%"
    filesystems:
        s3admin_fs:
            adapter: s3admin
            mount: s3admin_fs
        s3support_fs:
            adapter: s3support
            mount: s3support_fs
        s3blog_fs:
            adapter: s3blog
            mount: s3blog_fs
        s3policy_fs:
            adapter: s3policy
            mount: s3policy_fs

vich_uploader:
    db_driver: mongodb
    storage: flysystem
    mappings:
        adminS3Mapping:
            namer:
                service: vich_uploader.namer_property
                options: { property: 's3FileName'}
            upload_destination: s3admin_fs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        policyS3Mapping:
            namer:
                service: vich_uploader.namer_property
                options: { property: 's3FileName'}
            upload_destination: s3policy_fs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:
            - name: print-media-type
              value: true
    image:
        enabled:    false
        binary:     /usr/local/bin/wkhtmltopdf
        options:    []

scheb_two_factor:

    # Trusted computer feature
    trusted_computer:
        enabled: true                  # If the trusted computer feature should be enabled
        cookie_name: sosure-trusted    # Name of the trusted computer cookie
        cookie_lifetime: 604800          # Lifetime of the trusted computer cookie - 7 days

    # Regex pattern of paths you want to exclude from two-factor authentication.
    # Useful to exclude Assetic paths or other files from being blocked.
    # Example: ^/(css|js|images)/
    exclude_pattern: ^/(css|js|images)/

    # POST/GET parameter names
    parameter_names:
        auth_code: _auth_code          # Name of the parameter containing the authentication code
        trusted: _trusted              # Name of the parameter containing the trusted flag

    # Google Authenticator config
    google:
        enabled: true                      # If Google Authenticator should be enabled, default false
#        server_name: wearesosure.com       # Server name used in QR code
        issuer: "so-sure %kernel.environment%"   # Issuer name used in QR code
        template: SchebTwoFactorBundle:Authentication:form.html.twig   # Template used to render the authentication form

    # The service which is used to persist data in the user object. By default Doctrine is used. If your entity is
    # managed by something else (e.g. an API), you have to implement a custom persister
    persister: two_factor.persister

    # If your Doctrine user object is managed by a model manager, which is not the default one, you have to
    # set this option. Name of entity manager or null, which uses the default one.
    model_manager_name: ~

    # The security token classes, which trigger two-factor authentication.
    # By default the bundle only reacts to Symfony's username+password authentication. If you want to enable
    # two-factor authentication for other authentication methods, add their security token classes.
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

nexy_slack:

    # The Slack API Incoming WebHooks URL.
    endpoint:             "%slack_webhook%"

nelmio_security:
    csp:
        report_logger_service: monolog.logger.security
        enforce:
            # see full description below
            level1_fallback: true
            # only send directives supported by the browser, defaults to false
            # this is a port of https://github.com/twitter/secureheaders/blob/83a564a235c8be1a8a3901373dbc769da32f6ed7/lib/secure_headers/headers/policy_management.rb#L97
            browser_adaptive:
                enabled: true
            report-uri: "%router.request_context.base_url%/nelmio/csp/report"
            default-src:
                - 'self'
                - https://maxcdn.bootstrapcdn.com
                - https://www.digits.com
                - https://*.optimizely.com
                - https://js.intercomcdn.com
                - https://*.intercom.io
                - wss://*.intercom.io
                - wss://*.hotjar.com
                - https://app.getsentry.com
                - https://player.vimeo.com
                - https://*.facebook.com
                - http://*.facebook.com
                - https://api.prodpad.com
                - https://*.postcodeanywhere.co.uk
                - https://*.hotjar.com
                - https://*.google.ie
                - gsa://onpageload
                - https://*.doubleclick.net
                - https://*.hotjar.com 
                - https://*.google.ie
                - https://cdn.so-sure.com
                - https://www.youtube.com
                - https://*.fastly.net
                - https://maxcdn.bootstrapcdn.com
                - http://maxcdn.bootstrapcdn.com
                - 'data:'
            child-src:
                - 'self'
                - https://www.youtube.com
                - https://*.digits.com
                - http://*.facebook.com
                - https://player.vimeo.com
                - https://*.hotjar.com
            script-src:
                - 'self'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - https://cdn.so-sure.com
                - https://*.twimg.com
                - https://*.twitter.com
                - https://*.digits.com
                - https://ajax.googleapis.com
                - https://maxcdn.bootstrapcdn.com
                - https://www.googletagmanager.com
                - http://www.googletagmanager.com
                - https://app.prodpad.com
                - https://cdn.iubenda.com
                - http://cdn.iubenda.com
                - https://www.google-analytics.com
                - http://www.google-analytics.com
                - https://*.facebook.net
                - http://*.facebook.net
                - https://*.facebook.com
                - http://*.facebook.com
                - https://cdn.optimizely.com
                - http://cdn.optimizely.com
                - https://widget.intercom.io
                - https://js.intercomcdn.com
                - https://waitlisted.co
                - https://*.ads-twitter.com
                - https://*.hotjar.com
                - https://*.pcapredict.com
                - http://*.pcapredict.com
                - https://*.googleadservices.com
                - https://code.jquery.com
                - 'data:'
            style-src:
                - 'self'
                - 'unsafe-inline'
                - https://cdn.so-sure.com
                - https://maxcdn.bootstrapcdn.com
                - https://app.prodpad.com
                - https://cdn.digits.com
                - https://waitlisted.co
                - https://*.twitter.com
                - http://*.twitter.com
                - https://afeld.github.io
                - https://*.fastly.net
                - https://maxcdn.bootstrapcdn.com
                - http://maxcdn.bootstrapcdn.com
            img-src:
                - 'self'
                - https://cdn.so-sure.com
                - https://facebook.com
                - https://*.facebook.com
                - https://*.gravatar.com
                - https://*.wp.com
                - https://cdn.mxpnl.com
                - http://cdn.mxpnl.com
                - https://www.google-analytics.com
                - http://www.google-analytics.com
                - https://stats.g.doubleclick.net
                - https://heapanalytics.com
                - http://heapanalytics.com
                - https://*.twitter.com
                - http://*.twitter.com
                - https://*.twimg.com
                - https://www.google.com
                - https://www.google.co.uk
                - https://*.intercomassets.com
                - https://*.intercomcdn.com
                - https://t.co
                - https://*.doubleclick.net
                - https://*.googleadservices.com
                - https://*.fbcdn.net
                - 'data:'
                - https://*.google.ie
                - https://*.google.be

    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # prevents redirections outside the website's domain
    external_redirects:
        abort: true
        log: true
        whitelist:
            - sosure.app.link
            - facebook.com
            - sosure.test-app.link

    # forced HTTPS handling, don't combine with flexible mode
    # and make sure you have SSL working on your site before enabling this
#    forced_ssl:
#        hsts_max_age: 2592000 # 30 days
#        hsts_subdomains: true

    # flexible HTTPS handling, read the detailed config info
    # and make sure you have SSL working on your site before enabling this
#    flexible_ssl:
#        cookie_name: auth
#        unsecured_logout: false

dpn_xml_sitemap:
    additional_sitemaps:
        - help/sitemap.xml
        - blog/sitemap.xml
