imports:
    - { resource: config.yml }

framework:
    trusted_hosts: ['127.0.0.1', 'localhost', 'dev.so-sure.net', '10\.\d+\.\d+\.\d+']
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        #rollbar:
        #    type: service
        #    id: Rollbar\Monolog\Handler\RollbarHandler
        #    level: warning
        #    channels: ['!event']
        salva:
            type:   stream
            path:   "%kernel.logs_dir%/salva.log"
            level:  info
            channels: ["salva"]
        davies:
            type:   stream
            path:   "%kernel.logs_dir%/davies.log"
            level:  info
            channels: ["davies"]
        receperio:
            type:   stream
            path:   "%kernel.logs_dir%/receperio.log"
            level:  info
            channels: ["receperio"]
        main:
            formatter: "app.logger.lineformatter"
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
            channels: ["!event"]
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

swiftmailer:
    default_mailer: default
    mailers:
        default:
            delivery_address: "non-prod-web@so-sure.com"

snc_redis:
    profiler_storage:
        client: session
        ttl: 3600

#assetic:
#    filters:
#        uglifycss:
#            bin:        /usr/local/bin/uglifycss
#            apply_to:   '\.css$'

#nelmio_security:
#    forced_ssl:
#        hsts_max_age: 3600 # 30 days
#        hsts_subdomains: true
#        whitelist:
#            - ^/ops/status
