imports:
    - { resource: config.yml }

framework:
    # 10.* required for the elb load balancing health check
    # 127.0.0.1/localhost required for varnish health check
    trusted_hosts:
        - 'testing.wearesosure.com'
        - 'waterloo.testing.wearesosure.com'
        - 'monument.testing.wearesosure.com'
        - '127.0.0.1'
        - 'localhost'
        - '10\.\d+\.\d+\.\d+'
    router:
        resource: "%kernel.root_dir%/config/routing_errors.yml"
        strict_requirements: true
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
    session:
        cookie_secure: true

scheb_two_factor:
    trusted_computer:
        cookie_secure: true           # Set the 'Secure' (HTTPS Only) flag on the trusted_computer cookie

assetic:
    workers:
        cache_busting: ~

monolog:
    channels: ['receperio']
    handlers:
        #swift:
        #    type:       swift_mailer
        #    from_email: 'alert@so-sure.com'
        #    to_email:   'alert@so-sure.com'
        #    subject:    'Testing Error! %%message%%'
        #    level:      warning
        #    channels: ['!event']
        #    formatter:  monolog.formatter.html
        #    content_type: text/html
        rollbar:
            id: "app.logger.rollbar"
            formatter: "app.logger.lineformatter"
            type: rollbar
            level: warning
            channels: ['!event']
        salva:
            type:   stream
            path:   "%kernel.logs_dir%/salva.log"
            level:  info
            channels: ["salva"]
        davies:
            type:   stream
            path:   "%kernel.logs_dir%/davies.log"
            level:  info
            channels: ["davies"]
        receperio:
            type:   stream
            path:   "%kernel.logs_dir%/receperio.log"
            level:  info
            channels: ["receperio"]
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  info
            channels: ["!event"]
        console:
            type:  console

swiftmailer:
    default_mailer: default
    mailers:
        default:
            delivery_address: "non-prod-web@so-sure.com"

services:
    staging.apierror:
        class:   AppBundle\Listener\ApiResponseSubscriber
        arguments:
            - "@snc_redis.default"
        tags:
            - {name:kernel.event_subscriber}

nelmio_security:
    # forced HTTPS handling, don't combine with flexible mode
    forced_ssl:
        hsts_max_age: 3600 # 30 days
        hsts_subdomains: true
