imports:
    - { resource: config.yml }

framework:
    trusted_proxies:  [10.0.0.0/16]
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

staffim_rollbar:
    # Rollbar access token
    access_token: %rollbar_access_token%
    # PHP error level (see http://php.net/manual/en/function.error-reporting.php)
    error_level: -1
    # Values from scrub.parameters are replaced by the key for specified exceptions
    scrub:
        exceptions:
            - PDOException
        parameters:
            key: unknown