redirect_quote_samsung_7_edge:
    path: /phone-insurance/Samsung+Galaxy+S7+edge+32GB
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /phone-insurance/Samsung+Galaxy+S7+Edge+32GB
        permanent: true

appbundle:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
app:
    resource: "../../src/App/Controller/"
    type:     annotation
    prefix:   /

picsure:
    resource: "@PicsureMLBundle/Controller/"
    type:     annotation
    prefix:   /

nelmio_security:
    path:     /nelmio/csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods:  [POST]

DpnXmlSitemapBundle:
    resource: "@DpnXmlSitemapBundle/Resources/config/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_show:
    path: /user

fos_user_profile_edit:
    path: /user

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

fos_user_resetting_request:
    path: /resetting/request
    defaults:
        _controller: FOSUserBundle:Resetting:request
        method: GET

fos_user_resetting_send_email:
    path: /resetting/send-email
    defaults:
        _controller: AppBundle:FOSUser:sendEmail
#        _controller: FOSUserBundle:Resetting:sendEmail
        path: /send-email
        method: POST

fos_user_resetting_check_email:
    path: /resetting/check-email
    defaults:
        _controller: FOSUserBundle:Resetting:checkEmail
        method: GET

fos_user_resetting_reset:
    path: /resetting/reset/{token}
    defaults:
        _controller: AppBundle:FOSUser:reset
#        _controller: FOSUserBundle:Resetting:reset
        method: GET|POST

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

starling_login:
    path: /login/check-starling

accountkit_login:
    path: /login/check-accountkit

# FOSAuthServerBundle
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

redirect_homepage:
    path: /index.html
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true

redirect_terms_html:
    path: /terms.html
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: terms
        permanent: true

redirect_jobs_html:
    path: /jobs.html
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: careers
        permanent: true

_security_logout:
    path: /logout
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /logout
        permanent: true

redirect_launch:
    path: /launch/{id}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true

redirect_quote:
    path: /quote/{id}
    requirements:
        id: "[0-9a-f]{24,24}"
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: quote_phone
        permanent: true

redirect_quote_make_model_memory:
    path: /quote/{make}+{model}+{memory}+insurance
    requirements:
        make: "[a-zA-Z]+"
        model: "[+-.a-zA-Z0-9() ]+"
        memory: "[0-9]+"
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: quote_make_model_memory
        permanent: true

redirect_quote_make_model:
    path: /quote/{make}+{model}+insurance
    requirements:
        make: "[a-zA-Z]+"
        model: "[+-.a-zA-Z0-9() ]+"
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: quote_make_model
        permanent: true

redirect_jobs:
    path: /jobs
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: careers
        permanent: true

redirect_about_jobs:
    path: /about/social-insurance/jobs
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: careers
        permanent: true

redirect_terms:
    path: /terms
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: terms
        permanent: true

redirect_about_home:
    path: /about
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_are_we_regulated_within_the_uk:
    path: /about/are-we-regulated-within-the-uk
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_social_are_we_regulated_within_the_uk:
    path: /about/social-insurance/are-we-regulated-within-the-uk
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_how_secure_is_so_sure:
    path: /about/how-secure-is-so-sure
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_social_how_secure_is_so_sure:
    path: /about/social-insurance/how-secure-is-so-sure
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_the_team:
    path: /about/the-team
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_social_the_team:
    path: /about/social-insurance/the-team
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_how_to_contact_so_sure:
    path: /about/how-to-contact-so-sure
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_how_to_contact_so_sure
        permanent: true

redirect_about_our_mission:
    path: /about/our-mission
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_social_our_mission:
    path: /about/social-insurance/our-mission
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_why_we_re_better:
    path: /about/why-we-re-better
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_social_why_we_re_better:
    path: /about/social-insurance/why-we-re-better
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_what_is_social_insurance:
    path: /about/what-is-social-insurance
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_about_social_what_is_social_insurance:
    path: /about/social-insurance/what-is-social-insurance
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: about_home
        permanent: true

redirect_discount_vouchers:
    path: /discount-vouchers
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

redirect_blog_insuretech:
    path: /blog/2016/06/07/what-is-insurtech.html
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: https://blog.wearesosure.com/the-insurtech-revolution
        permanent: true

redirect_blog:
    path: /blog/{file}
    requirements:
        file: ".*"
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: https://blog.wearesosure.com/
        permanent: false # not convinced we may need to add additional redirects, so keep temp for now

redirect_change_password:
    path: /change-password
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: user_home
        permanent: true

redirect_help_centre:
    path: /help/{file}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: faq
        permanent: true
    requirements:
        file: .*

redirect_help_base_centre:
    path: /help
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: faq
        permanent: true

# https://symfony.com/doc/3.4/routing/redirect_trailing_slash.html with a 301
remove_trailing_slash:
    path: /{url}
    defaults:
        _controller: 'App\Controller\RedirectingController'
    requirements:
        url: .*/$

redirect_samsung_seven_edge_vodafone:
    path: /samsung-s7-insured-with-vodafone
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

redirect_pixel_vodafone:
    path: /google-pixel-insured-with-vodafone
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

redirect_iphone_se_vodafone:
    path: /iphone-SE-insured-with-vodafone
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

redirect_iphone_six_vodafone:
    path: /iphone-6-insured-with-vodafone
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

redirect_iphone_six_s_vodafone:
    path: /iphone-6s-insured-with-vodafone
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

redirect_iphone_seven_vodafone:
    path: /iphone-7-insured-with-vodafone
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

redirect_iphone_seven_s_vodafone:
    path: /iphone-7-plus-insured-with-vodafone
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true
