app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

DpnXmlSitemapBundle:
    resource: "@DpnXmlSitemapBundle/Resources/config/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

fos_user_resetting_request:
    path: /resetting/request
    defaults:
        _controller: FOSUserBundle:Resetting:request
        method: GET

fos_user_resetting_send_email:
    path: /resetting/send-email
    defaults:
        _controller: FOSUserBundle:Resetting:sendEmail
        path: /send-email
        method: POST

fos_user_resetting_check_email:
    path: /resetting/check-email
    defaults:
        _controller: FOSUserBundle:Resetting:checkEmail
        method: GET

fos_user_resetting_reset:
    path: /resetting/reset/{token}
    defaults:
        _controller: AppBundle:FOSUser:reset
#        _controller: FOSUserBundle:Resetting:reset
        method: GET|POST

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

facebook_login:
    path: /login/check-facebook

redirect_homepage:
    path: /index.html
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true

redirect_terms:
    path: /terms.html
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /terms
        permanent: true

redirect_jobs:
    path: /jobs.html
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /jobs
        permanent: true

_security_logout:
    path: /logout
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /logout
        permanent: true
    