# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user:
        class: AppBundle\Service\FOSUBUserProvider
        arguments: ["@fos_user.user_manager",{facebook: facebook_id}]
        
    app.mailchimp.prelaunch:
        class: AppBundle\Service\MailchimpService
        arguments:
          logger: "@logger"
          apikey: %mailchimp_apikey%
          list: %mailchimp_prelaunch_list%

    app.gocardless:
        class: AppBundle\Service\GocardlessService
        arguments:
            logger: "@logger"
            accessToken: %gocardless_apikey%
            prod: %gocardless_prod%

    app.judopay:
        class: AppBundle\Service\JudopayService
        arguments:
            doctrine: "@doctrine_mongodb"
            logger: "@logger"
            apiToken: %judopay_apitoken%
            apiSecret: %judopay_apisecret%
            judoId: %judopay_id%

    app.user.launch:
        class: AppBundle\Service\LaunchUserService
        arguments:
            doctrine: "@doctrine_mongodb"
            logger: "@logger"
            mailchimp: "@app.mailchimp.prelaunch"
            mailer: "@mailer"
            templating: "@templating"
            router: "@router"
            shortLink: "@app.shortlink"

    app.shortlink:
        class: AppBundle\Service\ShortLinkService
        arguments:
            logger: "@logger"
            googleAppName: %google_appname%
            googleApiKey: %google_apikey%
