namespaces:
  Rollerworks: Rollerworks\Component\PasswordStrength\Validator\Constraints\
  AppBundle: AppBundle\Validator\Constraints\

FOS\UserBundle\Model\User:
  properties:
    plainPassword:
      - Rollerworks:PasswordStrength: { minStrength: 4, minLength: 8, groups: [ ChangePassword, ResetPassword ], message: "Your password must be at least 8 characters and have a mixture of digits, special characters and uppercase and lower letters." }
#      - Expression: { expression: "!this.hasPreviouslyUsedPassword(4)", groups: [ ChangePassword, ResetPassword ], message: "Previous Password" }
#      - AppBundle:PreviousPassword: { versions: 4, groups: [ ChangePassword, ResetPassword ], message: "Your password can not be a previously used password." }
