- name: sosure web server
  hosts: all
  sudo: yes
  remote_user: ubuntu

  tasks:
    - name: ubuntu_idrsa
      sudo: no
      template: src=templates/id_rsa dest=/home/ubuntu/.ssh/id_rsa mode=0600
    - name: ubuntu_idrsapub
      sudo: no
      template: src=templates/id_rsa.pub dest=/home/ubuntu/.ssh/id_rsa.pub mode=0600
    - name: root_idrsa
      template: src=templates/id_rsa dest=/root/.ssh/id_rsa mode=0600
    - name: root_idrsapub
      template: src=templates/id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=0600
    - name: github_knownhost
      known_hosts: host='github.com' key="{{ lookup('file', 'pubkeys/github.com') }}" state='present'
    - name: gitlab_knownhost
      known_hosts: host='gitlab.com' key="{{ lookup('file', 'pubkeys/gitlab.com') }}" state='present'
    - name: nodesource
      apt_repository: repo='deb https://deb.nodesource.com/node_0.12 trusty main' state=present
    - name: nodesource-key
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
    - name: newrelic-source
      apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present
    - name: newrelic-source-key
      apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present
    - name: varnish-source
      apt_repository: repo='deb https://repo.varnish-cache.org/ubuntu/ precise varnish-3.0' state=present
    - name: varnish-source-key
      apt_key: url=https://repo.varnish-cache.org/GPG-key.txt state=present
    - name: mongo-source
      apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse' state=present
    - name: mongo-source-key
      apt_key:  keyserver=keyserver.ubuntu.com id=7F0CEB10
    - name: apt-update
      apt: update_cache=yes
    - name: base
      apt: pkg=apt-show-versions,nodejs,git,zip,libwww-perl,gcc,make,build-essential,imagemagick,mongodb-org-tools,ntp,ruby,ruby-dev,zlib1g-dev,msmtp,msmtp-mta,heirloom-mailx,python-pip,ansible,monit,newrelic-sysmond,varnish state=latest
    - name: apache php
      apt: pkg=apache2,php5,libapache2-mod-php5,php5-mcrypt,php-pear,php5-dev,php5-curl state=latest
    - name: for mongo pecl
      apt: pkg=pkg-config,libssl-dev,libsslcommon2-dev,libsasl2-dev,libpcre3-dev state=latest
    - name: apache modrewrite
      command: a2enmod rewrite
    - name: pecl mongo
      command: pecl install mongo 
    - name: php mongo
      template: src=templates/mongo.ini dest=/etc/php5/mods-available/mongo.ini
    - name: enable php mongo
      command: php5enmod mongo
    - name: s3cmd
      pip: name=s3cmd
    - name: security-ssh
      ufw: rule=allow port=22 proto=tcp
    - name: security-http
      ufw: rule=allow port=80 proto=tcp
    - name: security-https
      ufw: rule=allow port=443 proto=tcp
    - name: security-ufw-enable
      ufw: state=enabled
    - name: msmtprc
      template: src=templates/msmtprc dest=/etc/msmtprc
    - name: node-bower
      npm: name=bower global=yes
    - name: node-grunt
      npm: name=grunt global=yes
    - name: node-grunt-cli
      npm: name=grunt-cli global=yes
    - name: web-location
      file: path=/var/sosure owner=ubuntu group=ubuntu mode=0755 state=directory
    - name: web-location-release
      file: path=/var/sosure/release owner=ubuntu group=ubuntu mode=0755 state=directory
    - name: clone
      sudo: no
      git: repo=git@gitlab.com:urgsystems/sosure.git dest=/var/sosure/release/initial accept_hostkey=true force=yes
    - name: web-location-current
      file: dest=/var/sosure/current src=/var/sosure/release/initial owner=ubuntu group=ubuntu mode=0755 state=link
    - name: download-aws
      get_url: url=https://raw.githubusercontent.com/timkay/aws/master/aws dest=/usr/local/bin/aws mode=0755
    - name: download-memon
      get_url: url=https://raw.github.com/PeerJ/MEMon/master/memon.py dest=/usr/local/bin/memon.py mode=0755
    - name: boto
      pip: name=boto
    - name: boto-credentials
      template: src=templates/boto dest=/root/.boto mode=0640 owner=root      
    - name: stop-ntp
      service: name=ntp state=stopped
    - name: update-time
      command: ntpdate -s 0.ubuntu.pool.ntp.org
    - name: start-ntp
      service: name=ntp state=started
    - name: gem-msgpack
      command: gem install msgpack
    - name: gem-fluentd
      command: gem install fluentd -v "0.10.58"
    - name: gem-fluent-plugin-s3
      gem: name=fluent-plugin-s3 state=latest user_install=no
    - name: fluentd-group
      group: name=fluentd
    - name: fluentd-user
      user: name=fluentd groups=fluentd,adm
    - name: fluent-log
      file: path=/var/log/fluent owner=fluentd group=fluentd mode=0755 state=directory
    - name: fluent-etc
      file: path=/etc/fluent owner=fluentd group=fluentd mode=0755 state=directory
    - name: fluent-plugin-location
      file: path=/etc/fluent/plugin owner=fluentd group=fluentd mode=0755 state=directory
    - name: download-fluent-plugin-common
      get_url: url=https://raw.githubusercontent.com/PeerJ/fluent-plugin-common-log/master/lib/fluent/plugin/CommonLogFormatter.rb dest=/etc/fluent/plugin/CommonLogFormatter.rb mode=0644
    - name: fluentd-init
      template: src=templates/fluentd dest=/etc/init.d/fluentd mode=0755
    - name: restart-fluentd
      service: name=fluentd state=restarted
    - cron: name="boot_swap" special_time="reboot" job="/var/sosure/current/ansible/scripts/create-swap.sh 1024 >> /tmp/boot_swap.log"
    - name: download composer
      get_url: url=https://getcomposer.org/installer dest=/tmp/composer-install mode=0440
    - name: composer
      command: sudo php /tmp/composer-install --install-dir=/usr/local/bin --filename=composer
