- hosts: vagrant
  become: yes
  remote_user: ubuntu
  roles:
    - common
    - web
    - db
  tasks:
    - lineinfile: dest=/home/vagrant/.bashrc line="export SYMFONY_ENV=vagrant"
    - copy: src=/vagrant/web_app/app_vagrant.php dest=/vagrant/web/app.php
