- hosts: vagrant
  become: yes
  remote_user: ubuntu
  vars:
    - swap_file_path: /mnt/swap
    - swap_file_size: 524288
  roles:
    - common
    - web
    - db
  tasks:
    - lineinfile: dest=/home/vagrant/.bashrc line="export SYMFONY_ENV=vagrant"
    - lineinfile: dest=/home/vagrant/.bashrc line="alias webvagrant='/vagrant/ops/scripts/deploy.sh -C -n -u vagrant /vagrant vagrant';sudo /etc/init.d/apache2 restart"
    - copy: src=/vagrant/web_app/app_vagrant.php dest=/vagrant/web/app.php
    
    - name: Create swap file
      command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size }}
           creates="{{ swap_file_path }}"
      tags:
        - swap.file.create


    - name: Change swap file permissions
      file: path="{{ swap_file_path }}"
            owner=root
            group=root
            mode=0600
      tags:
        - swap.file.permissions


    - name: "Check swap file type"
      command: file {{ swap_file_path }}
      register: swapfile
      tags:
        - swap.file.mkswap


    - name: Make swap file
      command: "sudo mkswap {{ swap_file_path }}"
      when: swapfile.stdout.find('swap file') == -1
      tags:
        - swap.file.mkswap

    
    - name: Write swap entry in fstab
      mount: name=none
             src={{ swap_file_path }}
             fstype=swap
             opts=sw
             state=present
